<?php

namespace pro\armd\EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * UserAboutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAboutRepository extends EntityRepository
{
}
